# Generated by Django 5.1.1 on 2024-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="last_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
